### ISSUE TITLE
Feature request: disable parsing `node_modules`

### ISSUE THREAD

**Issue by mawkler** [dmmulroy/tsc.nvim#3]
Thanks for making a great plugin! I've noticed that it seems to also analyze code in `node_modules`. Is this intended behaviour? If yes, it would be awesome if there were an option to disable this 🙂

**Comment by dmmulroy** [comment]
Hey @mawkler, thanks for the feedback and issue! I'm considering adding support for this potentially via a configuration option. In the interim, you can update your `tsconfig` to ignore `node_modules` when `tsc` runs.

```json
{
  "compilerOptions": {... },
  "exclude": ["node_modules"]
}
```

**Comment by skdillon** [comment]
You should be able to do this now

```lua
require('tsc').setup({ flags: "--noEmit --excludeDirectories node_modules" })
```

**Comment by dmmulroy** [comment]
This issue is resolved thanks to your PR #8. Anyone that stumbles onto this issue you can now configured `tsc.nvim` as follows to ignore `node_modules`.

```lua
require("tsc").setup({ flags = "--noEmit --ignoreDirectories node_modules" })
```

**Comment by bezlant** [comment]
Hi, @dmmulroy the last solution doesn't seem to work. I get an error that there is not such a flag --ignoreDirectories. 
Any other ways to make it ignore the node_modules folder? 
I have the "exclude" in my config, but it stills keeps analysing the node_modules.
I guess I might be better off asking the official typescript compiler repo :P

**Comment by dmmulroy** [comment]
@bezlant ah yeah you're right, `--ignoreDirectories` is in fact not a `tsc` option.

You'll want the following in your `tsconfig`:

```json
{
  "compilerOptions": {
    "skipLibCheck": true
  },
}
```

Let me know if that doesn't work - happy to keep helping :)

**Comment by bezlant** [comment]
I appreciate the quick reply and help. The project has the skipLibCheck set to true, but it is still checking the node_modules. I have checked the config with tsc --showConfig and it indeed has the skipLibCheck flag. It is a huge monorepo, so there might be some caveats that have to be investigated. I have tried setting the project implicitly too, but it still fails to exclude the node_modules. For some reason I only get errors from the packages, that are built by us, and all the external packages seem to be not typechecked as intended (or they really don't have any errors). The tsc command take up to 30-45 seconds, so it could be checking the whole node_modules folder.

**Comment by dmmulroy** [comment]
If you run the `tsc` manually from the cli and point it at your `tsconfig.json`, do you experience the same issue?

**Comment by bezlant** [comment]
Yeah, it follows the same pattern.

**Comment by dmmulroy** [comment]
Yeah unfortunately if the typescript compiler is acting the same way on its own it's something with your project configuration and not the plug in then 😅 happy to try and help still if you can make a small repo where your issue is reproducible

**Comment by felipeospina21** [comment]
just for reference the following worked for me, without modifying the tsConfig
```lua
require('tsc').setup({
  flags = {
    noEmit = true,
    skipLibCheck = true,
  }
})
```
